[package]
authors     = ["Travis Zhang<https://github.com/travzhang>"]
description = ""
edition     = "2021"
license     = "MIT"
name        = "swc-plugin-coverage"
repository  = "https://github.com/canyon-project/swc-plugin-istanbul"
version     = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc-coverage-instrument = { workspace = true }
serde_json              = { workspace = true }
swc_core                = { workspace = true, features = ["ecma_plugin_transform"] }
tracing                 = { workspace = true }
tracing-subscriber      = { workspace = true, features = ["fmt"] }
typed-path              = { workspace = true }
wax                     = { workspace = true }
