[package]
authors     = ["Travis Zhang<https://github.com/travzhang>"]
description = ""
edition     = "2021"
license     = "MIT"
name        = "swc-coverage-instrument"
repository  = "https://github.com/canyon-project/swc-plugin-istanbul"
version     = "0.0.1"

[dependencies]
once_cell      = { workspace = true }
regex          = "1.8.1"
serde          = { workspace = true, features = ["derive"] }
serde_json     = { workspace = true }
swc_atoms      = { workspace = true }

swc_core = { workspace = true, features = [
  "common",
  "ecma_quote",
  "ecma_visit",
  "ecma_utils",
  "ecma_ast",
] }
tracing = "0.1.37"

[dev-dependencies]
pretty_assertions = "1.3.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(swc_ast_unknown)'] }
